Proyectos (Unidad 4)/myapp/urls.py
from django.conf import settings
from django.urls import path
from . import views
#from django.contrib.staticfiles.urls import static
from django.conf.urls.static import static

app_name="proyect"

urlpatterns = [
     path('', views.login, name="login"),

     path('crear/', views.crear.as_view(), name="crear"),
     path('portafolio/', views.portafolio, name="portafolio2"),
     path('registro/', views.registro.as_view(), name="registro"),

     path('cerrar_sesion/', views.cerrar_sesion, name="cerrar_sesion"),

     path('portafolio_general/', views.portafolio_general, name="portafolio_general"),

      path('delete/<int:id>', views.delete, name="delete"),
      path('edit/<int:id>', views.edit.as_view(), name="edit"),

 
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyectos (Unidad 4)/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myapp.urls")),
]

urlpatterns +=staticfiles_urlpatterns()

Proyectos (Unidad 4)/myapp/models.py
from django.db import models


class Proyecto(models.Model):
    titulo=models.CharField(max_length=400)
    foto=models.ImageField(upload_to="images")
    descripcion=models.CharField(max_length=400)
    tag=models.CharField(max_length=400)
    url=models.CharField(max_length=400)

Proyectos (Unidad 4)/myapp/forms.py
from django import forms


class FormularioEntregable(forms.Form):

    titulo=forms.CharField(label="Título del proyecto", required=True)
    foto=forms.ImageField(label="Foto (URL)")
    descripcion=forms.CharField(label="Descripción del proyecto ", widget=forms.Textarea)
    tag=forms.CharField(label="TAGS", required=True)
    url=forms.CharField(label="URL de github", required=True)

Proyectos (Unidad 4)/myapp/views.py
from django.views import View
from django.http import HttpResponse, request
from django.shortcuts import render,redirect
from .forms import FormularioEntregable
from .models import Proyecto
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login as dj_login , logout
from django.contrib import messages


# Create your views here.

class crear(View):
    template = "crear.html"
    context = {"form": FormularioEntregable}

    def get(self, request):
        
        return render(request, self.template, self.context)

    def post(self, request):
        form=FormularioEntregable(request.POST or None, request.FILES or None)
       
        if form.is_valid():
            
            proyect=Proyecto()
            
            proyect.titulo=form.cleaned_data["titulo"]
            proyect.foto=form.cleaned_data["foto"]
            proyect.descripcion=form.cleaned_data["descripcion"]
            proyect.tag=form.cleaned_data["tag"]
            proyect.url=form.cleaned_data["url"]
            print(proyect.foto)
            proyect.save()

            return redirect("proyect:portafolio2")
        
        return HttpResponse("no valido")
    

def portafolio(request):
        proyectos_registrados=Proyecto.objects.all()

        return render(request, "portafolio.html", {"registros":proyectos_registrados})
  
class registro(View):

    def get(self, request):
        form=UserCreationForm()
        return render(request, "registro.html", {"form":form})

    def post(self, request):
        form=UserCreationForm(request.POST)

        if form.is_valid():

            usuario=form.save()

            dj_login(request,usuario)
            return redirect("proyect:crear")

        else:
            for msg in form.error_messages:
                messages.error(request,form.error_messages[msg])

            return render(request, "registro.html", {"form":form})

def login(request):

    if request.method == "POST":
        form=AuthenticationForm(request, request.POST)
        if form.is_valid():
            nombre_usuario=form.cleaned_data.get("username")
            contra=form.cleaned_data.get("password")
            usuario=authenticate(username=nombre_usuario, password=contra)
            if usuario is not None:
                dj_login(request, usuario)
                return redirect("crear/")
            else:
                messages.error(request, "usuario no válido")

        else:
            messages.error(request, "información incorrecta")

        #return redirect("crear/")


    form=AuthenticationForm()
    return render(request, "login.html", {"form":form})

def cerrar_sesion(request):
    logout(request)

    return redirect("proyect:login")



def portafolio_general(request):

    proyectos_registrados=Proyecto.objects.all()
    return render(request, "portafolio_general.html", {"registros":proyectos_registrados})
    


def delete(request, id):

    form_filter=Proyecto.objects.filter(id=id)
    form_filter.delete()
    return redirect("proyect:portafolio2")

class edit(View):
 
    def get(self, request, id):
        form_filter=Proyecto.objects.filter(id=id)[0]

        return render(request, "edit.html", {"proyecto":form_filter})

    def post(self, request, id):
        
        titulo=request.POST["titulo"]
        tag=request.POST["tag"]
        descripcion=request.POST["descripcion"]
        url=request.POST["url"]
        #foto=request.POST["foto"]  #si quito el enctype y pongo foto=request.POST["foto"] entonces cuando yo ponga en el html : <td>{{item.foto.url}}</td>  esto me da /media/foto.jpg -> es decir to me da lo correcto que sería -> /media/images/foto.jpg
        foto=request.FILES["foto"]  #el enctype hace que yo pueda subir de forma correcta a mi bbdd para que después pueda ser leído y mostrar la foto

        proyect=Proyecto.objects.filter(id=id)[0]
        
        proyect.titulo=titulo
        proyect.foto=foto      #si lees la línea 124 y piensas ponerle proyect.foto="images/"+ request.POST["foto"] entonces pensarías que funcionaría pero no es así. por eso vuelve a leer la línea 125
        proyect.descripcion=descripcion         
        proyect.tag=tag     
        proyect.url=url
        print(proyect.foto)
        proyect.save()

    

        return redirect("proyect:portafolio2")





       
        

Proyectos (Unidad 4)/myapp/templates/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
     <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
    </head>
    <body>

    {%if user.is_authenticated %}

        <nav class="nav">
        <a class="nav-link" href="{% url 'proyect:cerrar_sesion' %}" >LOG OUT</a>
        <a class="nav-link" href="{% url 'proyect:portafolio_general' %}" >VER FORTALIO GENERAL</a>
        <a class="nav-link" href="{% url 'proyect:portafolio2' %}" >VER PROYECHOS HECHOS</a>
        <a class="nav-link" href="{% url 'proyect:crear' %}" >Agregar proyecto</a>
        </nav>
    
    {% else %}

    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">REGISTRO</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'proyect:login' %}">Log in</a>
            </div>
            </div>
        </div>
    </nav>

    {% endif %}

    {% block content %}{% endblock %}

    </body>
</html>

Proyectos (Unidad 4)/myapp/templates/crear.html
{% extends "base.html" %}

{% block content %}

{% comment %} 
<nav class="nav">
  <a class="nav-link" href="{% url 'proyect:cerrar_sesion' %}" >LOG OUT</a>
  <a class="nav-link disabled">FORMULARIO</a>
</nav> {% endcomment %}


<h1 align="center">FORMULARIO PROYECTO</h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table style="color: black; margin: 20px auto;">{{form.as_table}}</table> 
    <center><input type="submit" value="Crear proyecto" style="width: 150px;"></center>

</form>


  {% endblock %}

Proyectos (Unidad 4)/myapp/templates/edit.html
{% extends "base.html" %}

{% block content %}

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="modal-header">						
        <h4 class="modal-title">Edit PROYECT</h4>
        
    </div>
    <div class="modal-body">					
        <div class="form-group">
            <label> TITULO PROYECTO</label>
            <input type="text" class="form-control" name ="titulo" id="titulo" value={{proyecto.titulo}} required>
        </div>
        <div class="form-group">
            <label>TAG</label>
            <input type="text" class="form-control" id="tag" name ="tag" value={{proyecto.tag}} required>
        </div>
        <div class="form-group">
            <label>DESCRIPCION</label>
            <textarea class="form-control" id="descripcion" name ="descripcion" required>{{proyecto.descripcion}}</textarea>
        </div>
        <div class="form-group">
            <label>URL</label>
            <input type="text" class="form-control"id="url" name ="url"  value={{proyecto.url}} required>
        </div>		

        <div class="form-group">
            <label>FOTO</label>
            <input type="file" accept="image/*" class="form-control" name ="foto" id="foto" required>
        </div>				
    </div>
    <div class="modal-footer">
        <a href="{% url 'proyect:portafolio2' %}"><input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel"></a>
        <input type="submit" class="btn btn-info" value="Save">
    </div>

</form>


{% endblock %}

Proyectos (Unidad 4)/myapp/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/x-icon" href="{% static 'imagenes/logo-vt.svg' %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bootstrap Login Page</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
  </head>
  <body class="bg-info d-flex justify-content-center align-items-center vh-100">

  <form action="" method="post" >
    {% csrf_token %}
    <div
      class="bg-white p-5 rounded-5 text-secondary shadow"
      style="width: 25rem"
    >
      <div class="d-flex justify-content-center">
        <img
          src="{% static 'imagenes/login-icon.svg' %}"
          alt="login-icon"
          style="height: 7rem"
        />
      </div>
      <div class="text-center fs-1 fw-bold">Login</div>
      <div class="input-group mt-4">
        <div class="input-group-text bg-info">
          <img
            src="{% static 'imagenes/username-icon.svg' %}"
            alt="username-icon"
            style="height: 1rem"
          />
        </div >
     
        {{form.username}}
  

      </div>
      <div class="input-group mt-1">
        <div class="input-group-text bg-info">
          <img
            src="{% static 'imagenes/password-icon.svg' %}"
            alt="password-icon"
            style="height: 1rem"
          />
        </div>
        {{form.password}}
      </div>
      <div class="d-flex justify-content-around mt-1">
        <div class="d-flex align-items-center gap-1">
          <input class="form-check-input" type="checkbox" />
          <div class="pt-1" style="font-size: 0.9rem">Remember me</div>
        </div>
        <div class="pt-1">
          <a
            href="#"
            class="text-decoration-none text-info fw-semibold fst-italic"
            style="font-size: 0.9rem"
            >Forgot your password?</a
          >
        </div>
      </div>
      <div >
        <button type="submit" class="btn btn-info text-white w-100 mt-4 fw-semibold shadow-sm">Login</button>
      </div>
      <div class="d-flex gap-1 justify-content-center mt-1">
        <div>Don't have an account?</div>
        <a href="{% url 'proyect:registro' %}" class="text-decoration-none text-info fw-semibold"  
          >Register</a
        >
      </div>

 


    </form>
    <br>
    <b> USER: brian <br>
    contra: 1234 </b> 
  </body>
</html>

Proyectos (Unidad 4)/myapp/templates/portafolio.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<style>
<style>
	table.table td a.edit {
        color: #FFC107;
    }
    table.table td a.delete {
        color: #F44336;
    }
    table.table td i {
        font-size: 19px;
    }
</style>

<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">TITULO PROYECTO</th>
      <th scope="col">TAG</th>
      <th scope="col">DESCRIPCION</th>
      <th scope="col">URL</th>
      <th scope="col">FOTO</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>

    <form action="" method="POST">

    {% for item in registros %}
    <tr>
      {% comment %} <input id="prodId" name="prodId" type="hidden" value="{{item.titulo}}"> {% endcomment %}
      <th scope="row">{{item.id}}</th>
      <td>{{item.titulo}}</td>
      <td>{{item.tag}}</td>
      <td>{{item.descripcion}}</td>
      <td>{{item.url}}</td>
      <td><img src="{{ item.foto.url }}" alt="", height="100"></td>
			<td>
				<a href="{% url 'proyect:edit' item.id %}" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
				<a href="{% url 'proyect:delete' item.id %}" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
			</td>
    </tr>
    {% endfor %}

    </form>
  </tbody>
</table>


  {% endblock %}

Proyectos (Unidad 4)/myapp/templates/registro.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}


<form action="" method="post" >
    {% csrf_token %}

    <div style="width: 75%; margin: auto;">

    {{form|crispy}}

    <button type="submit">Registrar</button>
    
    </div>


</form>
  {% endblock %}