Proyectos (Unidad 3)/Ricky_morty/app/models/personajes.py
import datetime

class Personajes:
    def __init__(self,id,name,status,species,type,gender,origin,location,image,episode,url,created):
        self.id=id
        self.name=name
        self.status=status
        self.species=species
        self.type=type
        self.gender = gender
        self.origin = origin
        self.location = location
        self.image = image
        self.episode = episode
        self.url = url
        self.created = created

        
    def to_json(self):
        return {
            'id':self.id,
            'name':self.name,
            'status':self.status,
            'species':self.species,
            'type':self.type,
            'gender':self.gender,
            'origin':self.origin,
            'location':self.location,
            'image':self.image,
            'episode':self.episode,
            'url':self.url,
            'created':self.created

        }
    

class Capitulo:
    def __init__(self,id,name,air_date,episode,characters,url,created):
        self.id=id
        self.name=name
        self.air_date=air_date
        self.episode = episode
        self.characters = characters
        self.url = url
        self.created = created

        
    def to_json(self):
        return {
            'id':self.id,
            'name':self.name,
            'air_date':self.air_date,
            'episode':self.episode,
            'characters':self.characters,
            'url':self.url,
            'created':self.created
        }
    

Proyectos (Unidad 3)/Ricky_morty/app/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap  #2
from app.config import Config
from .routes.ricky_morty import personajes_ruta
import hashlib
from app.db import db

def create_app():
    app=Flask(__name__)
    app.config.from_object(Config)

    Bootstrap(app)                      #2

    app.register_blueprint(personajes_ruta)
        
    return app

Proyectos (Unidad 3)/Ricky_morty/app/routes/ricky_morty.py
from flask import Blueprint,render_template, request, flash
from app.models.personajes import Personajes, Capitulo
from app.db import db
import requests
personajes_ruta=Blueprint("personajes_ruta", __name__)


@personajes_ruta.route("/")
def index():
    personajes=db.personajes.find().sort('id', -1)
    return render_template("index.html", personajes=personajes) 

@personajes_ruta.route("/insertar")
def insertar():

    

    for n in range(1,22):

        url="https://rickandmortyapi.com/api/character?page="
            
        url_personaje=url+ str(n)
        response= requests.get(url_personaje)
        datos=response.json()
        

        for y in datos["results"]:
            infor=Personajes(y["id"], y["name"], y["status"], y["species"], y["type"], y["gender"], y["origin"]["url"], y["location"]["name"], y["image"], y["episode"], y["url"], y["created"])
            db.personajes.insert_one(infor.to_json())
            #lista_personajes.append()

    return "PERSONAJES INGRESADOS"


def gravatar(id=""):
    url = "https://rickandmortyapi.com/api/character/avatar/"
    url=url + str(id) + ".jpeg"
        
    return "{url}".format(url=url)


@personajes_ruta.route("/avatar/<id>")
def avatar(id):
    id=int(id)
    filtro=db.personajes.find({"id":id})

    avt = gravatar(id)
    return render_template("avatar.html", avatar=avt, info=filtro)



#--------------------------------------------------EJERCICIO ADICIONAL--------------------------------------------------------------

@personajes_ruta.route("/insertar_capitulos")
def insertar_capitulos():


    for n in range(1,4):

        url="https://rickandmortyapi.com/api/episode?page="
            
        url_capitulos=url+ str(n)
        response= requests.get(url_capitulos)
        datos=response.json()
        

        for y in datos["results"]:
            infor=Capitulo(y["id"], y["name"], y["air_date"], y["episode"], y["characters"],y["url"], y["created"])
            db.capitulos.insert_one(infor.to_json())

    return "CAPITULOS INGRESADOS"

@personajes_ruta.route("/capitulo/<id>")
def personajes_capitulo(id):
                                                                                    #en los 2 variables "personajes_lista" me dueleve algo así > ['https://rickandmortyapi.com/api/character/1', 'https://rickandmortyapi.com/api/character/2']
    #personajes_lista=db.capitulos.find()[int(id)]["characters"]                    #Aquí uso ["characters"] porque estoy buscando en un diccionario, En html pondría .characters porque así se manejo en html
    #print(db.capitulos.find()[1])                                                  # -> me da el documento con id 2 (porque [1] es el índiceque busca en una lista) 
    personajes_lista=db.capitulos.find({"id":int(id)})[0]["characters"]             # db.capitulos.find({"id":int(id)}) = me da un objeto, por eso tengo que poner "[0]" y me arrojaría el documento, luego con el ["characters"] me arroja solo los capitulos 
                                                                                    # db.capitulos.find() = me da un objeto
    informacion_url=[]                                                              #PREGUNTA : poque tengo que usar [0]: quizás porque en ese objeto hay un elemento en una lista
    for url_personaje in personajes_lista:                                 

        try:                                                
            url=url_personaje
            response= requests.get(url)
            datos=response.json()
            informacion_url.append(datos)
        
        except requests.exceptions.JSONDecodeError:
            informacion_url.append("not found")   
            

    return render_template("personajes_capitulo.html", informacion_url=informacion_url, id=id) 

Proyectos (Unidad 3)/Ricky_morty/app/templates/avatar.html
<!DOCTYPE html>

<html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>PERSONAJES RICK AND MORTY</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/static/estilos.css" >

    </head>
    <body>
         <div class="padre">
                  <div class="tarjeta">
                      <div class="titulo">{{info[0].name}}</div>
                      <div class="cuerpo">
                      <img src="{{info[0].image}}" alt="muestra">
                      </div>
                      <div class="pie">
                          SPECIES: {{info[0].species}} <br> 
                          GENDER: {{info[0].gender}} <br> 
                          STATUS: {{info[0].status}} <br> 
                      </div>
                  </div>
        </div>

    </body>
</html>

Proyectos (Unidad 3)/Ricky_morty/app/templates/index.html
<!DOCTYPE html>

<html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>PERSONAJES RICK AND MORTY</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/static/estilos.css" >
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet"/>
    </head>
    <body>
        <h1 align="center">PERSONAJES RICK AND MORTY</h1>
        <div class="container">
            <div class="row">

                {% for i in personajes %}
                
                <div class="col-md-4">
                    <div class="tarjeta">
                        <div class="titulo">{{i.name}}</div>
                        <div class="cuerpo">
                        <img src="{{i.image}}" alt="muestra">
                        </div>
                        <div class="pie">
                        <a href="{{url_for('personajes_ruta.avatar', id=i.id)}}">Más información</a>
                        </div>
                    </div>
                </div>
            
                {% endfor %}
            </div>
        </div>
  
    </body>
</html>

Proyectos (Unidad 3)/Ricky_morty/app/templates/personajes_capitulo.html
<!DOCTYPE html>

<html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>PERSONAJES RICK AND MORTY</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/static/estilos.css" >
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet"/>
    </head>
    <body>
        <h1 align="center">CAPITULO {{id}}</h1>
        <div class="container">
            <div class="row">

                {% for i in informacion_url %}
                
                <div class="col-md-4">
                    <div class="tarjeta">
                        <div class="titulo">{{i.name}}</div>
                        <div class="cuerpo">
                        <img src="{{i.image}}" alt="muestra">
                        </div>
                      <div class="pie">
                          TYPE: {{i.type}} <br> 
                          SPECIES: {{i.species}} <br> 
                          GENDER: {{i.gender}} <br> 
                          STATUS: {{i.status}} <br> 
                      </div>
                    </div>
                </div>
            
                {% endfor %}
            </div>
        </div>
  
    </body>
</html>